default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fit_schedule_development

test:
  <<: *default
  database: fit_schedule_test

production:
  <<: *default
  database: fit_schedule_production
  username: fit_schedule
  password: <%= ENV['FIT_SCHEDULE_DATABASE_PASSWORD'] %>
